[project]
name = "expense-tracker"
version = "0.1.0"
description = "This is a Expense tracker for mcp server."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.14.1",
]
